notmuch: disable perl test dependency
If this is here, the build on NetBSD breaks with

In file included from gmime-filter-reply.c:21:
gmime-filter-reply.h:22:10: fatal error: gmime/gmime-filter.h: No such file or directory
   22 | #include <gmime/gmime-filter.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

after

Checking for available C compiler warning flags...
        -Wall -Wextra -Wwrite-strings -Wmissing-declarations
./configure: perl_absolute: parameter not set
./configure: perl_absolute: parameter not set


Disable test target as well.